spring:
  application:
    name: dev-portal

  jackson:
    mapper:
      accept-case-insensitive-enums: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      host: mongodb-prod.mongo
      port: 27017
      database: dev-portal
      username: dev_user
      password: prod!@#qlalfqjsgh486!
      authentication-database: admin

  datasource:
    url: jdbc:mysql://192.168.100.100:30307/sys?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dev_user
    password: qlalfqjsgh!486
    driver-class-name: com.mysql.cj.jdbc.Driver