spring:
  application:
    name: dev-portal

  jackson:
    mapper:
      accept-case-insensitive-enums: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  data:
    mongodb:
      host: mongodb-dev.mongo
      port: 27017
      database: dev-portal
      username: dev_user
      password: devqlalfqjsgh486
      authentication-database: admin